CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS oil_platforms (
    id UUID PRIMARY KEY NOT NULL DEFAULT (uuid_generate_v4()),
    platform_type VARCHAR(255) NOT NULL,
    platform_level SMALLINT NOT NULL DEFAULT 0,
    profitability BIGINT NOT NULL DEFAULT 10,
    created_at BIGINT DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    updated_at BIGINT DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
);