CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE money_transactions (
    id UUID PRIMARY KEY NOT NULL DEFAULT (uuid_generate_v4()),
    item_id UUID NOT NULL,
    amount BIGINT NOT NULL,
    created_at BIGINT DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    updated_at BIGINT DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
);